### ISSUE TITLE
チャットが流れていく問題について

### ISSUE THREAD

**Issue by Minamix** [notsmatch/KyoshuBot#11]
.start等で募集を進行させた後、.everyone .here 等でもう一度募集のチャットをさせる事等はできますでしょうか。
画像のように、募集のチャットがどんどん流れていってしまう状況なので、もし可能であればそういった機能が欲しいです。

![image](https://user-images.githubusercontent.com/65997752/82982215-a6745800-a028-11ea-82fd-f0d58bd314da.png)

**Comment by notsmatch** [comment]
> .start等で募集を進行させた後、.everyone .here 等でもう一度募集のチャットをさせる事等はできますでしょうか。
> 画像のように、募集のチャットがどんどん流れていってしまう状況なので、もし可能であればそういった機能が欲しいです。
> 
> ![image](https://user-images.githubusercontent.com/65997752/82982215-a6745800-a028-11ea-82fd-f0d58bd314da.png)

Issues書き込みありがとうございます。
募集メッセージ再送信のコマンドを実装させていただくと思います

**Comment by Minamix** [comment]
ありがとうございます。
実装のほうお待ちしております。

**Comment by notsmatch** [comment]
implemented
