### ISSUE TITLE
挙手取り下げのコマンドがチャットに残る

### ISSUE THREAD

**Issue by Louix-lnt** [notsmatch/KyoshuBot#12]
![Screenshot_2020-05-27-17-21-32-46_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/66006865/83000422-4d66ed00-a045-11ea-9f2c-ebdede99cc55.png)
タイトルの通りになります
.dコマンドを使用すると反映はされますがコマンドの履歴がチャットから削除されず残ったままとなります
ご確認頂けると幸いです

**Comment by notsmatch** [comment]
> ![Screenshot_2020-05-27-17-21-32-46_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/66006865/83000422-4d66ed00-a045-11ea-9f2c-ebdede99cc55.png)
> タイトルの通りになります
> .dコマンドを使用すると反映はされますがコマンドの履歴がチャットから削除されず残ったままとなります
> ご確認頂けると幸いです

https://github.com/notsmatch/KyoshuBot/releases/tag/1.0.4 からの変更上の仕様です。
表示切り替えできるようにします。

**Comment by notsmatch** [comment]
https://github.com/notsmatch/KyoshuBot/releases/tag/1.0.6
