### ISSUE TITLE
挙手をしているメンバーに通知を送る

### ISSUE THREAD

**Issue by Minamix** [notsmatch/KyoshuBot#13]
![835EB301-4791-4257-B6D8-50463E44C2F1](https://user-images.githubusercontent.com/65997752/83097561-5a3a1e00-a0e3-11ea-97a0-fd35632254e1.jpeg)

例えばですが、
21時のメンバーが集まった際に、一人一人に何分開設かとか伝えなきゃいけないけど、普通にタイピングするよりなにか便利な方法はないかなと考えました。
.notify hour message
のような感じで、送りたい交流戦の時間と、メッセージを伝えるようなことが出来るともう少し便利になるかなと思います。

**Comment by notsmatch** [comment]
> ![835EB301-4791-4257-B6D8-50463E44C2F1](https://user-images.githubusercontent.com/65997752/83097561-5a3a1e00-a0e3-11ea-97a0-fd35632254e1.jpeg)
> 
> 例えばですが、
> 21時のメンバーが集まった際に、一人一人に何分開設かとか伝えなきゃいけないけど、普通にタイピングするよりなにか便利な方法はないかなと考えました。
> .notify hour message
> のような感じで、送りたい交流戦の時間と、メッセージを伝えるようなことが出来るともう少し便利になるかなと思います。

挙手状況 21: Aさん Bさん Cさん

.notify 21 <message>
↓
KyoshuBot: 「21: @Aさん @Bさん @Cさん <message>」

ということであってるのならば、実装できますよ。

**Comment by notsmatch** [comment]
> ![835EB301-4791-4257-B6D8-50463E44C2F1](https://user-images.githubusercontent.com/65997752/83097561-5a3a1e00-a0e3-11ea-97a0-fd35632254e1.jpeg)
> 
> 例えばですが、
> 21時のメンバーが集まった際に、一人一人に何分開設かとか伝えなきゃいけないけど、普通にタイピングするよりなにか便利な方法はないかなと考えました。
> .notify hour message
> のような感じで、送りたい交流戦の時間と、メッセージを伝えるようなことが出来るともう少し便利になるかなと思います。

挙手状況 21: Aさん Bさん Cさん

.notify 21 <message>
↓
KyoshuBot: 「21: @Aさん @bさん @Cさん  <message>」

ということであってるのならば、実装できますよ。

**Comment by notsmatch** [comment]
> ![835EB301-4791-4257-B6D8-50463E44C2F1](https://user-images.githubusercontent.com/65997752/83097561-5a3a1e00-a0e3-11ea-97a0-fd35632254e1.jpeg)
> 
> 例えばですが、
> 21時のメンバーが集まった際に、一人一人に何分開設かとか伝えなきゃいけないけど、普通にタイピングするよりなにか便利な方法はないかなと考えました。
> .notify hour message
> のような感じで、送りたい交流戦の時間と、メッセージを伝えるようなことが出来るともう少し便利になるかなと思います。

挙手状況 21: Aさん Bさん Cさん

.notify 21 message
↓
KyoshuBot: 「21: @Aさん @bさん @Cさん message」

ということであってるのならば、実装できますよ。

**Comment by Minamix** [comment]
そういう感じです🙏
ぜひお願いします🙇‍♂️
