### ISSUE TITLE
管理者がメンションを指定して、挙手を上げ下げする機能・notifyコマンドの改行対応

### ISSUE THREAD

**Issue by notsmatch** [notsmatch/KyoshuBot#15]
![Screenshot_5](https://user-images.githubusercontent.com/46530214/83121748-ad28cb00-a10d-11ea-9977-14f6a75af956.png)

**Comment by notsmatch** [comment]
改行対応うまくいきません

**Comment by notsmatch** [comment]
管理者がメンションを指定して、挙手を上げ下げする機能 実装できました

**Comment by MotherCP** [comment]
もろもろありがとうございます！

**Comment by notsmatch** [comment]
> もろもろありがとうございます！

こちらこそ、いろんなアイデアありがとうございます！また何かございましたら書き込んでください！
