### ISSUE TITLE
時間ごとに〆る昨日

### ISSUE THREAD

**Issue by MotherCP** [notsmatch/KyoshuBot#18]
.endで全ての募集が締め切られるが

.end 21 で21のみ強制的に締める

**Comment by MotherCP** [comment]
昨日→機能

**Comment by MotherCP** [comment]
> .endで全ての募集が締め切られるが
> 
> .end 21 で21のみ強制的に締める

**Comment by notsmatch** [comment]
.close になるかもです

**Comment by notsmatch** [comment]
コマンド実行時、既に満員の場合でもプログラム側では強制的に締め切り判定にする
