### ISSUE TITLE
notifiコマンド　コメント先指定

### ISSUE THREAD

**Issue by MotherCP** [notsmatch/KyoshuBot#19]
.nofity #693769167198748732 21 あああああ

チャンネルIDを指定するとその指定先チャンネルにBOTからのコメントが書き込まれる。

**Comment by MotherCP** [comment]
チャンネルIDはDiscordの設定を開発者モードにすれば見れます

**Comment by notsmatch** [comment]
.setnotifychannel <id> でデータベース保存します

**Comment by MotherCP** [comment]
すいません理解できませんでした。
