### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by MotherCP** [notsmatch/KyoshuBot#22]
①複数挙手（.c 20 21 22 23）が反応しないことがまれにある。
特に時間を飛ばすと漏れていることが多いです（,c 20 22 23）

②数分間BOTが落ちていることがある

**Comment by notsmatch** [comment]
デバッグしてませんでした🤦なおします

**Comment by notsmatch** [comment]
② https://github.com/notsmatch/KyoshuBot/issues/23 移行
